### ISSUE TITLE
Print out hello word on select query

### ISSUE THREAD

**Issue by steveoni** [systemEng-Learning/postgres-redis#2]

**Comment by goodyduru** [comment]
In trying to initialize this repo on a Macbook Pro 2019 version 11.7.8 using this command `cargo pgrx init`, I got a clang error. I solved this by just installing postgres.app from this [website](https://postgresapp.com/downloads.html). I made sure to install the release with all the supporting versions. 

I ran `which pg_config` to get its location which is something like this `/Applications/Postgres.app/Contents/Versions/latest/bin//pg_config`. All I have to do is to replace the 'latest' in the path with the version I want e.g `/Applications/Postgres.app/Contents/Versions/15/bin//pg_config` for Postgres v15. This is important, as it is used when initializing the different versions using pgrx.

To initialize all the available and supported versions (11-16) with pgrx, I ran this command

> cargo pgrx init --pg11 /Applications/Postgres.app/Contents/Versions/11/bin//pg_config --pg12 /Applications/Postgres.app/Contents/Versions/12/bin//pg_config --pg13 /Applications/Postgres.app/Contents/Versions/13/bin//pg_config --pg14 /Applications/Postgres.app/Contents/Versions/14/bin//pg_config --pg15 /Applications/Postgres.app/Contents/Versions/15/bin//pg_config --pg16 /Applications/Postgres.app/Contents/Versions/16/bin//pg_config

After successfully doing this, I set up the initial files in this repo.
